
version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
   version: 3.7
   install:
     - requirements: docs/requirements.txt
     - requirements: requirements/requirements.txt
#     - method: pip
#       path: .
#       extra_requirements:
#         - snowmobile
